# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: mmistakes/minimal-mistakes@4.26.2
minimal_mistakes_skin: dark


# Site settings
locale:                  "en-US"
title:                   "Tero Korpela"
title_separator:         "-"
subtitle:                "Portfolio"
name:                    &name "Tero Korpela" # &name is a YAML anchor which can be *referenced later
description:             &description "Here is my portfolio"
url:                     "https://terokorp.github.io"
baseurl:                 ""
repository:              "terokorp/terokorp.github.io"
teaser:                  # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo:                    # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title:          # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs:           false # true, false (default)
words_per_minute:        200
enable_copy_code_button: true

atom_feed:
  path:                  # blank (default) uses feed.xml

# Social Sharing
twitter_username:   "Thachan"
github_username:    "terokorp"
linkedin_username:  "tero-korpela"

# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/Thachan"
    - "https://www.linkedin.com/in/tero-korpela"
    - "https://github.com/terokorp"


# Site Author
author:
  name: "Tero Korpela"
  avatar: "/assets/images/bio-photo-tk.jpg"
  bio: " " # Note: Markdown is allowed
  location: "Jyväskylä, Finland"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/terokorp"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tero-korpela"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/terokorp"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tero-korpela"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:          kramdown
highlighter:       rouge
lsi:               false
excerpt_separator: "\n\n"
incremental:       false

# Markdown Processing
kramdown:
  input:           GFM
  hard_wrap:       false
  auto_ids:        true
  footnote_nr:     1
  entity_output:   as_char
  toc_levels:      1..6
  smart_quotes:    lsquo,rsquo,ldquo,rdquo
  enable_coderay:  false

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
    
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Helsinki

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-tagories

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development